#과제
# 여기에 코드를 작성하세요
class Myclass :
    def __init__(self, txt):
        self.__txt = txt
        
    def getter(self):
        return self.__txt
    
    def setter(self, __txt):
        self.__txt = txt
    
    def __str__(self):
        return "Print: {}".format(self.__txt)

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
from makedata import *

In [5]:
get_name()

'Andrew'

In [6]:
get_age()

34

In [7]:
df1=pd.DataFrame(make_data(5))
df2=pd.DataFrame(make_data(5))
df1

Age     Name
0   40  Anthony
1   39  Anthony
2   39     Alan
3   35    Alvin
4   21      Jin

In [8]:
df3=df1.append(df2)

In [9]:
df3[:5]

Age     Name
0   40  Anthony
1   39  Anthony
2   39     Alan
3   35    Alvin
4   21      Jin

In [10]:
df3.reset_index(drop=True,inplace=True)

In [11]:
df3

Age     Name
0   40  Anthony
1   39  Anthony
2   39     Alan
3   35    Alvin
4   21      Jin
5   22      Jin
6   36   Arnold
7   35     Adam
8   23     Alex
9   23     Adam

In [12]:
df3.tail(2)

Age  Name
8   23  Alex
9   23  Adam

In [13]:
df3=pd.concat([df1,df2]).reset_index(drop=True)

In [14]:
df3

Age     Name
0   40  Anthony
1   39  Anthony
2   39     Alan
3   35    Alvin
4   21      Jin
5   22      Jin
6   36   Arnold
7   35     Adam
8   23     Alex
9   23     Adam

In [15]:
df1

Age     Name
0   40  Anthony
1   39  Anthony
2   39     Alan
3   35    Alvin
4   21      Jin

In [16]:
df2

Age    Name
0   22     Jin
1   36  Arnold
2   35    Adam
3   23    Alex
4   23    Adam

In [18]:
pd.concat([df3,df1],axis=1,join='inner')

Age     Name  Age     Name
0   40  Anthony   40  Anthony
1   39  Anthony   39  Anthony
2   39     Alan   39     Alan
3   35    Alvin   35    Alvin
4   21      Jin   21      Jin

In [19]:
df=pd.DataFrame(make_data())

In [20]:
df

Age    Name
0   35    Alan
1   39  Arnold
2   39    Adam
3   39    Alan
4   23    Adam
5   25   Alvin
6   28  Andrew
7   28  Anchal
8   20  Anchal
9   40    Alan

In [27]:
result_df=df.groupby("Name").size().reset_index(name="counts")

In [28]:
result_df

Name  counts
0    Adam       2
1    Alan       3
2   Alvin       1
3  Anchal       2
4  Andrew       1
5  Arnold       1

In [30]:
result_df.sort_values(["counts","Name"],ascending=False,inplace=True)

In [31]:
result_df.reset_index(drop=True, inplace=True)

In [32]:
result_df

Name  counts
0    Alan       3
1  Anchal       2
2    Adam       2
3  Arnold       1
4  Andrew       1
5   Alvin       1

In [35]:
df.groupby("Name").agg("mean").reset_index()

Name  Age
0    Adam   31
1    Alan   38
2   Alvin   25
3  Anchal   24
4  Andrew   28
5  Arnold   39

In [36]:
df.describe()

Age
count  10.000000
mean   31.600000
std     7.633261
min    20.000000
25%    25.750000
50%    31.500000
75%    39.000000
max    40.000000

In [38]:
import makedata

In [39]:
makedata.get_age(), makedata.get_name()

(36, 'Alvin')

In [40]:
makedata.make_data()

[{'Age': 27, 'Name': 'Anchal'},
 {'Age': 31, 'Name': 'Anthony'},
 {'Age': 31, 'Name': 'Arnold'},
 {'Age': 37, 'Name': 'Anchal'},
 {'Age': 25, 'Name': 'Alan'},
 {'Age': 40, 'Name': 'Alan'},
 {'Age': 25, 'Name': 'Anthony'},
 {'Age': 25, 'Name': 'Adam'},
 {'Age': 29, 'Name': 'Jin'},
 {'Age': 20, 'Name': 'Anchal'}]

#### quiz
- makedata 모듈을 이용해서 데이터 프레임 만들기
- user_df
    - 8명의 데이터가 있는 데이터 프레임을 만드세요.
    - UserID : 1 ~ 8
    - Name : makedata.get_name()
    - Age  : makedata.get_age()
    - 중복되는 Name 값이 없도록

In [41]:
#딕셔너리의 리스트 : UserID, Name , Age
datas={}
datas["UserID"] = list(range(1,9))
datas["Age"]=[makedata.get_age() for _ in range(8)]
names= []
while True :
    name = makedata.get_name()
    if name not in names :
        names.append(name)
    if len(names) >=8:
        break
datas["Name"]=names

user_df=pd.DataFrame(datas)
user_df




UserID  Age     Name
0       1   36   Arnold
1       2   35     Alex
2       3   24  Anthony
3       4   33   Anchal
4       5   23     Alan
5       6   32   Andrew
6       7   21     Adam
7       8   35    Alvin

In [43]:
#딕셔너리 데이터를 데이터 프레임에 하나씩추가하기 : UserID, Name, Age
user_df=pd.DataFrame(columns=["UserID","Name","Age"])

for idx in range(1,9):
    name=makedata.get_name()
    while name in list(user_df["Name"]):
        name = makedata.get_name()
    data={"Name":name, "UserID":idx,"Age":makedata.get_age()}
    
    user_df.loc[len(user_df)]=data
user_df


UserID    Name Age
0      1     Jin  29
1      2   Billy  37
2      3  Arnold  35
3      4   Alvin  23
4      5    Alex  38
5      6  Andrew  30
6      7    Alan  34
7      8    Adam  23

#### quiz
- money_df 만들기
    - 15개의 데이터
    - ID : 1 ~ 8 랜덤한 숫자 데이터
    - Money : 1000원 단위로 1000원 ~ 20000원까지의 숫자가 저장

In [46]:
# 딕셔너리 데이터를 데이터 프레임에 하나씩 추가하기
money_df = pd.DataFrame(columns=["ID", "Money"])
#np.random.randint(1,9)
for _ in range(15):
    money_df.loc[len(money_df)] = {
        "ID":np.random.randint(1,9),
        "Money":np.random.randint(1,21) * 1000
    }
ids=money_df["ID"].unique()
ids.sort()
len(ids),ids

(7, array([1, 2, 4, 5, 6, 7, 8], dtype=object))

In [47]:
money_df

ID  Money
0   4  15000
1   4  14000
2   5  17000
3   1  12000
4   4   5000
5   8  16000
6   1  11000
7   2  14000
8   7   4000
9   4  10000
10  8   6000
11  6   1000
12  5   7000
13  1  14000
14  6   8000

In [48]:
user_df

UserID    Name Age
0      1     Jin  29
1      2   Billy  37
2      3  Arnold  35
3      4   Alvin  23
4      5    Alex  38
5      6  Andrew  30
6      7    Alan  34
7      8    Adam  23

In [53]:
user_df.merge(money_df,left_on="UserID",right_on="ID")

UserID    Name Age ID  Money
0       1     Jin  29  1  12000
1       1     Jin  29  1  11000
2       1     Jin  29  1  14000
3       2   Billy  37  2  14000
4       4   Alvin  23  4  15000
5       4   Alvin  23  4  14000
6       4   Alvin  23  4   5000
7       4   Alvin  23  4  10000
8       5    Alex  38  5  17000
9       5    Alex  38  5   7000
10      6  Andrew  30  6   1000
11      6  Andrew  30  6   8000
12      7    Alan  34  7   4000
13      8    Adam  23  8  16000
14      8    Adam  23  8   6000

In [54]:
user_df.rename(columns={"UserID":"ID"},inplace=True)

In [55]:
user_df.tail(1)

ID  Name Age
7  8  Adam  23

In [56]:
user_df.merge(money_df).tail(2)

ID  Name Age  Money
13  8  Adam  23  16000
14  8  Adam  23   6000

In [57]:
result_df=pd.merge(money_df,user_df)

In [61]:
result_df

ID  Money    Name Age
0   4  15000   Alvin  23
1   4  14000   Alvin  23
2   4   5000   Alvin  23
3   4  10000   Alvin  23
4   5  17000    Alex  38
5   5   7000    Alex  38
6   1  12000     Jin  29
7   1  11000     Jin  29
8   1  14000     Jin  29
9   8  16000    Adam  23
10  8   6000    Adam  23
11  2  14000   Billy  37
12  7   4000    Alan  34
13  6   1000  Andrew  30
14  6   8000  Andrew  30

In [59]:
money_list=result_df.groupby("Name").sum()["Money"].reset_index()

In [60]:
money_list

Name  Money
0    Adam  22000
1    Alan   4000
2    Alex  24000
3   Alvin  44000
4  Andrew   9000
5   Billy  14000
6     Jin  37000

In [62]:
result=pd.merge(user_df,money_list,how="outer")

In [63]:
result

ID    Name Age    Money
0  1     Jin  29  37000.0
1  2   Billy  37  14000.0
2  3  Arnold  35      NaN
3  4   Alvin  23  44000.0
4  5    Alex  38  24000.0
5  6  Andrew  30   9000.0
6  7    Alan  34   4000.0
7  8    Adam  23  22000.0

In [64]:
#fillna :NaN을 특정 데이터로 채워줌

In [65]:
result.fillna(value=0,inplace=True)

In [66]:
result

ID    Name  Age    Money
0   1     Jin   29  37000.0
1   2   Billy   37  14000.0
2   3  Arnold   35      0.0
3   4   Alvin   23  44000.0
4   5    Alex   38  24000.0
5   6  Andrew   30   9000.0
6   7    Alan   34   4000.0
7   8    Adam   23  22000.0

In [67]:
result.dtypes

ID         int64
Name      object
Age        int64
Money    float64
dtype: object

In [68]:
result["Money"]=result["Money"].astype("int")

In [69]:
result

ID    Name  Age  Money
0   1     Jin   29  37000
1   2   Billy   37  14000
2   3  Arnold   35      0
3   4   Alvin   23  44000
4   5    Alex   38  24000
5   6  Andrew   30   9000
6   7    Alan   34   4000
7   8    Adam   23  22000

In [73]:
result.sort_values("Money",ascending=False,inplace=True)

In [76]:
result.reset_index(drop=True,inplace=True)

In [77]:
result

ID    Name  Age  Money
0   4   Alvin   23  44000
1   1     Jin   29  37000
2   5    Alex   38  24000
3   8    Adam   23  22000
4   2   Billy   37  14000
5   6  Andrew   30   9000
6   7    Alan   34   4000
7   3  Arnold   35      0

In [78]:
np.average(result.sort_values("Money",ascending=False)[:3]["Age"])

30.0

In [80]:
#load
titanic=pd.read_csv("train.csv")
titanic.tail(2)

PassengerId  Survived  Pclass                   Name   Sex   Age  SibSp  \
889          890         1       1  Behr, Mr. Karl Howell  male  26.0      0   
890          891         0       3    Dooley, Mr. Patrick  male  32.0      0   

     Parch  Ticket   Fare Cabin Embarked  
889      0  111369  30.00  C148        C  
890      0  370376   7.75   NaN        Q

In [82]:
#save
titanic.to_csv("titanic.tsv",sep="\t",index=False)

In [83]:
#load : encoding
df=pd.read_csv("2014_p.csv",encoding="euc-kr")

In [84]:
df

ID RCTRCK     RACE_DE  RACE_NO  PARTCPT_NO  RANK RCHOSE_NM HRSMN  \
0          1     부경  2014-01-03       12           6   8.0      프리마돈   설동복   
1          2     부경  2014-01-03        8           2   8.0      중앙최강   이성재   
2          3     부경  2014-01-03        8           1  11.0      맹호소리   김태경   
3          4     부경  2014-01-03        5           9   1.0    스마트에너지   후지이   
4          5     부경  2014-01-03        4           3   3.0     금포스카이   유현명   
...      ...    ...         ...      ...         ...   ...       ...   ...   
27213  27214     제주  2014-11-29        9           4   2.0      황용신화   이재웅   
27214  27215     제주  2014-11-29        4           5   2.0      백록장원   장우성   
27215  27216     제주  2014-11-29        4           3   7.0      산정무한   안득수   
27216  27217     제주  2014-11-29        9           7   6.0      미주여행   김경휴   
27217  27218     제주  2014-11-29        9           6   1.0       철옹성   장우성   

           RCORD ARVL_DFFRNC           EACH_SCTN_PASAGE_RANK  \
0      0:02:07.5          머리       8 - 7 - 4 - 5 - 5 - 4 - 4   
1      0:01:39.1           ½   11 -  - 11 - 11 - 12 - 10 - 8   
2      0:01:42.3           5  10 -  - 10 - 10 - 11 - 11 - 11   
3      0:01:02.0         NaN          8 -  -  -  - 8 - 7 - 2   
4      0:01:25.5           4        4 -  - 3 - 7 - 7 - 4 - 4   
...          ...         ...                             ...   
27213  0:01:27.1          2½             4 -  -  - 5 - 5 - 2   
27214  0:01:19.9          머리             7 -  -  - 7 - 6 - 4   
27215  0:01:22.8          1½             4 -  -  - 4 - 4 - 6   
27216  0:01:31.1          13             2 -  -  - 2 - 3 - 6   
27217  0:01:26.6         NaN             1 -  -  - 1 - 1 - 1   

       A_WIN_SYTM_EXPECT_ALOT  WIN_STA_EXPECT_ALOT  
0                        16.9                  4.7  
1                        30.2                  5.1  
2                        99.8                  9.1  
3                         3.3                  1.3  
4                         3.4                  1.2  
...                       ...                  ...  
27213                     1.8                  2.2  
27214                     3.5                  1.3  
27215                    30.9                  5.2  
27216                     6.2                  9.4  
27217                     3.9                  2.9  

[27218 rows x 13 columns]

In [85]:
df.tail(2)

ID RCTRCK     RACE_DE  RACE_NO  PARTCPT_NO  RANK RCHOSE_NM HRSMN  \
27216  27217     제주  2014-11-29        9           7   6.0      미주여행   김경휴   
27217  27218     제주  2014-11-29        9           6   1.0       철옹성   장우성   

           RCORD ARVL_DFFRNC EACH_SCTN_PASAGE_RANK  A_WIN_SYTM_EXPECT_ALOT  \
27216  0:01:31.1          13   2 -  -  - 2 - 3 - 6                     6.2   
27217  0:01:26.6         NaN   1 -  -  - 1 - 1 - 1                     3.9   

       WIN_STA_EXPECT_ALOT  
27216                  9.4  
27217                  2.9

In [86]:
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [88]:
#group by
df1=titanic.groupby(["Sex","Pclass"]).size().reset_index(name="counts")
df1

Sex  Pclass  counts
0  female       1      94
1  female       2      76
2  female       3     144
3    male       1     122
4    male       2     108
5    male       3     347

In [95]:
#pivot
result = df1.pivot("Sex","Pclass","counts")

In [96]:
result

Pclass    1    2    3
Sex                  
female   94   76  144
male    122  108  347

In [97]:
#pivot table 이용
titanic["counts"]=1
titanic.tail(2)

PassengerId  Survived  Pclass                   Name   Sex   Age  SibSp  \
889          890         1       1  Behr, Mr. Karl Howell  male  26.0      0   
890          891         0       3    Dooley, Mr. Patrick  male  32.0      0   

     Parch  Ticket   Fare Cabin Embarked  counts  
889      0  111369  30.00  C148        C       1  
890      0  370376   7.75   NaN        Q       1

In [98]:
result = titanic.pivot_table("counts",["Pclass"],["Survived"],aggfunc=np.sum)

In [99]:
result

Survived    0    1
Pclass            
1          80  136
2          97   87
3         372  119

In [100]:
result["total"]=result[0] + result[1]

In [101]:
result

Survived    0    1  total
Pclass                   
1          80  136    216
2          97   87    184
3         372  119    491

In [102]:
result.loc["total"]=result.loc[1] + result.loc[2] + result.loc[3]

In [103]:
result

Survived    0    1  total
Pclass                   
1          80  136    216
2          97   87    184
3         372  119    491
total     549  342    891

In [104]:
import numpy as np

In [105]:
data1 = np.array([80,85,100,90,95])
data2 = np.array([70,80,100,95,95])

In [106]:
# variance code
def variance(data) :
    avg = np.average(data)
    var= 0
    
    for num in data :
        var += (num - avg) ** 2
        
    return var / len(data)

In [108]:
variance(data1),variance(data2),variance(data1) ** 0.5, variance(data2) **0.5

(50.0, 126.0, 7.0710678118654755, 11.224972160321824)

In [109]:
np.var(data1),np.var(data2),np.std(data1),np.std(data2)

(50.0, 126.0, 7.0710678118654755, 11.224972160321824)

In [110]:
p_data1= np.random.randint(60,100,int(1E5))

In [111]:
p_data2=np.random.randint(60,100,int(1E5))

In [112]:
%%time
variance(p_data1),variance(p_data2)

Wall time: 684 ms


(132.84084459509583, 133.32982057439335)

In [113]:
%%time
np.var(p_data1), np.var(p_data2)

Wall time: 1.96 ms


(132.8408445951, 133.3298205744)

In [114]:
data1 = np.array([80, 85, 100, 90, 95])
data2 = np.array([70, 80, 100, 95, 95])
np.cov(data1, data2)[0, 1]

93.75

In [115]:
data3 = np.array([80, 85, 100, 90, 95])
data4 = np.array([100, 90, 70, 90, 80])
np.cov(data3, data4)[0, 1]

-87.5

In [116]:
df = pd.read_csv("premierleague.csv")


In [117]:
df.tail()

name  gf  ga  points
15     Huddersfield Town  28  58      37
16           Southampton  37  56      36
17          Swansea City  28  56      33
18            Stoke City  35  68      33
19  West Bromwich Albion  31  56      31

In [119]:
#득점
gf=np.array(df["gf"])
gf

array([106,  68,  74,  84,  62,  74,  36,  44,  56,  39,  45,  45,  48,
        44,  34,  28,  37,  28,  35,  31], dtype=int64)

In [120]:
#실점
ga=np.array(df["ga"])

In [121]:
ga

array([27, 28, 36, 38, 38, 51, 39, 58, 60, 47, 55, 61, 68, 64, 54, 58, 56,
       56, 68, 56], dtype=int64)

In [122]:
#승점
points=np.array(df["points"])
points

array([100,  81,  77,  75,  70,  63,  54,  49,  47,  44,  44,  44,  42,
        41,  40,  37,  36,  33,  33,  31], dtype=int64)

In [123]:
data1, data2=np.corrcoef(gf,points)[0,1] **2 , np.corrcoef(ga,points)[0,1] **2

In [124]:
data1, data2

(0.8683266496886471, 0.757933920368845)

In [125]:

round(data1,2), round(data2,2)

(0.87, 0.76)

In [126]:
import pickle
# 선형회귀 모델
from sklearn import linear_model
# 학습 데이터와 테스트 데이터를 나눠주는 모듈
from sklearn.model_selection import train_test_split
# 모델을 평가해주는 모듈
from sklearn.metrics import mean_absolute_error

In [144]:
# 1. 데이터 로드
p_df = pd.read_csv("premierleague.csv")
p_df

name   gf  ga  points
0            Manchester City  106  27     100
1          Manchester United   68  28      81
2          Tottenham Hotspur   74  36      77
3                  Liverpool   84  38      75
4                    Chelsea   62  38      70
5                    Arsenal   74  51      63
6                    Burnley   36  39      54
7                    Everton   44  58      49
8             Leicester City   56  60      47
9           Newcastle United   39  47      44
10            Crystal Palace   45  55      44
11               Bournemouth   45  61      44
12           West Ham United   48  68      42
13                   Watford   44  64      41
14  Brighton and Hove Albion   34  54      40
15         Huddersfield Town   28  58      37
16               Southampton   37  56      36
17              Swansea City   28  56      33
18                Stoke City   35  68      33
19      West Bromwich Albion   31  56      31

In [128]:
# 2. 데이터 전처리 1 : 독립변수, 종속변수 나누기
df_x = p_df[["gf","ga"]]
df_y = p_df[["points"]]

In [131]:
# 2. 데이터 전처리 2 : 학습 데이터와 테스트 데이터로 나누기
train_x, test_x, train_y, test_y =train_test_split(
    df_x, df_y, test_size=0.3, random_state=1)

In [132]:
model = linear_model.LinearRegression()

In [145]:
model

LinearRegression()

In [133]:
model.fit(train_x, train_y)

LinearRegression()

In [134]:
pred_y=model.predict(test_x)

In [135]:
pred_y

array([[80.88065736],
       [40.79778662],
       [50.9467527 ],
       [46.31419247],
       [76.04209484],
       [40.23228639]])

In [136]:
test_y["points"].values

array([75, 36, 54, 44, 77, 40], dtype=int64)

In [138]:
pred_y = np.around(pred_y.flatten()).astype("int")
pred_y

array([81, 41, 51, 46, 76, 40])

In [140]:
mae=mean_absolute_error(test_y,pred_y)
round(mae,2)

2.83

In [141]:
#예측함수
def make_df(gf,ga):
    return pd.DataFrame({"gf":[gf],"ga":[ga]})

In [142]:
gf,ga=80,30
result =int(model.predict(make_df(gf,ga)).flatten()[0])

In [143]:
result

83